### ISSUE TITLE
small annoyances.

### ISSUE THREAD

**Issue by aileen-fisher** [adjtomo/pysep#107]
In your documentation: https://adjtomo.github.io/pysep/pysep.html, 

pysep -p MTUQ2022_workshop -e 2017-09-03T033001_NORTH_KOREA.yaml  is wrong.  Should be mtuq_workshop_2022.

Also, 'pysep -W' will overwrite another saved config file of the same name without asking.  It should ask if overwrite is ok or just add something to the end of the new file name.

**Comment by bch0w** [comment]
Hi @aileen-fisher, thanks for pointing those out! I've pushed a few changes to the latest `devel` branch that fixes the docs and does not let users write over existing files with -W unless they use the -o flag as well. 

These will be included in the next official version release.

**Comment by bch0w** [comment]
Closing as this has been addressed in the latest version. Please re-open if you're still encountering these issues!
