### ISSUE TITLE
"weights.dat" file not being generated

### ISSUE THREAD

**Issue by Rinku-274** [adjtomo/pysep#118]
The capability to generate weight files during data download is missing in the latest version of PySEP. Please consider adding the functionality to create weight files while downloading the data.

**Comment by bch0w** [comment]
Hi @Rinku-274, thanks for bringing this up, the ability to generate 'weights.dat' files is still there but has been turned off by default, to turn it back on using a Config file, you just need to add the following line:

``` yaml
write_files: inv,event,stream,sac,weights_code
```

If using PySEP directly in a Python script, you would do

```python
from pysep import Pysep
ps = Pysep(*args, **kwargs, write_files="inv,event,stream,sac,weights_code")
```

You can substitute 'weights_code' for 'weights_dist' and 'weights_az' to sort your weights file by distance or azimuth, respectively. You can find the available options for the `write_files` argument here: https://github.com/adjtomo/pysep/blob/master/pysep/pysep.py#L399-L422

I do admit this is not very transparent for the User and is not mentioned in the Docs anywhere. I will create a new issue to provide some better documentation about how to access this.

**Comment by Rinku-274** [comment]
Thank you @bch0w for your prompt response and valuable suggestions. I've successfully obtained the weight files now.

**Comment by bch0w** [comment]
Closing as completed
