### ISSUE TITLE
QOL improvements to RecSec file reading capabilities

### ISSUE THREAD

**Issue by bch0w** [adjtomo/pysep#122]
Small quality of life updates for RecSec file reading. RecSec has slightly restrictive requirements for its input file reading:

- Synthetics can only be read in as SPECFEM ASCII files - allow reading in Globe-version SAC files
- Real data must have the '.sac' file extension (case-sensitive). Allow this file extension to be whatever (.SAC, '')

**Comment by ammcpherson** [comment]
Hi @bch0w,

I can now confirm that I can plot synthetic SAC files - thank you so much for implementing this!

-Amanda
