### ISSUE TITLE
Iceland example correct depth

### ISSUE THREAD

**Issue by SeismoFelix** [adjtomo/pysep#126]
Hi Bryant, 

Tiny thing:
For the event in Iceland, the depth should be 5km, not 50km. I guess it was a typo. 

Thanks, 

Felix

**Comment by SeismoFelix** [comment]
For the North Korea example, the window is too short (300s) for the waveforms that can be retrieved. Probably 1000s is more appropriate. 

1000s record section:
<img width="887" alt="Screenshot 2023-10-30 at 10 47 20 PM" src="https://github.com/adjtomo/pysep/assets/18186011/20801b55-a56d-412d-84cf-9e47abe435bc">

300s record section:
<img width="893" alt="Screenshot 2023-10-30 at 10 20 11 PM" src="https://github.com/adjtomo/pysep/assets/18186011/296c9b29-acda-4ee8-9dcf-c746e72c6f6c">

**Comment by bch0w** [comment]
Hi @SeismoFelix, these are addressed in the latest devel branch with commit b0daad7

**Comment by SeismoFelix** [comment]
Thanks Bryant, 

To point out that these modifications are not available when installing Pysep via pip. It is something expected?
Thanks

**Comment by bch0w** [comment]
No problem! Yep that is expected, I manually push releases to Pip when we get enough changes to warrant it, so all of the current changes in `devel` are not reflected in Pip installs until then. But I've been meaning to get a version release out so expect that soon!

**Comment by SeismoFelix** [comment]
Ok. So the best course of action, I think,  is to copy some of your parameters files locally, make some slight modifications (windows length, _legacy_naming, etc.), and run pysep -c.  Thank you so much.

**Comment by bch0w** [comment]
Hi @SeismoFelix, the latest changes should now be available via Pip. Wondering if it's okay to close this issue?

**Comment by SeismoFelix** [comment]
Wonderful, yes, thanks a lot.

**Comment by bch0w** [comment]
Perfect! Closing as complete
