### ISSUE TITLE
missing SAC headers while reading SPECFEM3D_cartesian data

### ISSUE THREAD

**Issue by aakash10gupta** [adjtomo/pysep#132]
It looks like pysep (read_sem) is not reading in available information into SAC headers while reading in data from SPECFEM3D_cartesian. This probably happens when the source/stations are defined in the cartesian coordinate system instead of the geographical coordinate system. The missing headers include 'b' and 'evdp' among other possible missing headers.

**Comment by bch0w** [comment]
Hi @aakash10gupta, this should be fixed in #138, can you test and let me know if you are able to access the new SAC headers for Cartesian synthetics?

**Comment by aakash10gupta** [comment]
Hi @bch0w, yes I'm able to access the new SAC headers.
