### ISSUE TITLE
recsec: preprocess flag masks the functioning of other flags

### ISSUE THREAD

**Issue by aakash10gupta** [adjtomo/pysep#133]
In recsec, a number of flags like `integrate`, etc. do not work unless the `preprocess` flag is also set. Sometimes, having to set the preprocess flag can be redundant as well as unintuitive, to have the "sub-flags" work. At least, a warning message asking to set the `preprocess` flag, if any of the "sub-flags" are used without setting the `preprocess` flag, should help.

**Comment by bch0w** [comment]
This has been updated in #139, additional sub flags are availble for turning off different parts of the processing workflow. You can find the options in the main docstring of RecSec

**Comment by aakash10gupta** [comment]
I think this new approach should be helpful.
