### ISSUE TITLE
Pysep somewhat randomly matching components of 2 sets of synthetics together

### ISSUE THREAD

**Issue by ammcpherson** [adjtomo/pysep#135]
Hello,

I recently was trying to plot a record section of 2 sets of synthetics together. One set had the naming convention *.HX?.semd and the other *.BX?.semd, and I noticed that, according to the debugging output for the relative amplitude information, Pysep was somewhat randomly plotting mismatching components (and stations!) together. For example:

```[2024-02-20 17:28:41] - pysep - DEBUG: relative amplitude information
IDX        [O]BS          [S]YN     [O_A]BSMAX  [S_A]BSMAX   O_A/S_A   LN(O_A/S_A)
1   XX.R01-03..BXZ XX.R01-01..HXY    1.71E-17    7.19E-05    2.37E-13   -2.91E+01
5   XX.R01-03..BXY XX.R01-03..HXY    1.17E-18    2.67E-06    4.38E-13   -2.85E+01
7   XX.R01-03..BXX XX.R01-03..HXX    2.89E-17    4.05E-02    7.13E-16   -3.49E+01
0   XX.R01-02..BXZ XX.R01-01..HXX    1.16E-17    7.03E-02    1.65E-16   -3.63E+01
6   XX.R01-02..BXY XX.R01-02..HXX    1.14E-17    5.51E-02    2.07E-16   -3.61E+01
8   XX.R01-02..BXX XX.R01-01..HXZ    3.99E-17    8.43E-05    4.73E-13   -2.84E+01
4   XX.R01-01..BXZ XX.R01-02..HXY    7.18E-19    1.59E-02    4.52E-17   -3.76E+01
3   XX.R01-01..BXY XX.R01-02..HXZ    9.60E-19    1.71E-02    5.61E-17   -3.74E+01
2   XX.R01-01..BXX XX.R01-03..HXZ    4.98E-17    2.42E-02    2.06E-15   -3.38E+01
```

This was done doing the command `recsec --pysep_path ./E_force_axi/ --syn_path ./E_force/ --source ./FORCESOLUTION --stations ./STATIONS --synsyn --overwrite --sort_by azimuth --scale_by global_norm --preprocess both --min_period_s 2 --components X,Y,Z` for the attached directory.

This problem was solved by renaming one set of synthetics to match the other (so both sets had the naming convention *.HX?.semd)

Thanks!
[name_mismatch_test.tar.zip](https://github.com/adjtomo/pysep/files/14364396/name_mismatch_test.tar.zip)

**Comment by bch0w** [comment]
Hi @ammcpherson, thanks for the detailed issue report and the example data/command, makes it really easy to test this out! 

Unfortunately I am unable to recreate the issues you're seeing, and am getting what seems like the correct ordering with the different channel names:

```bash
IDX        [O]BS          [S]YN     [O_A]BSMAX  [S_A]BSMAX   O_A/S_A   LN(O_A/S_A)
7   XX.R01-03..BXZ XX.R01-03..HXZ    1.71E-02    2.42E-02    7.05E-01   -3.49E-01
5   XX.R01-03..BXY XX.R01-03..HXY    1.17E-03    2.67E-06    4.38E+02    6.08E+00
2   XX.R01-03..BXX XX.R01-03..HXX    2.89E-02    4.05E-02    7.13E-01   -3.39E-01
3   XX.R01-02..BXZ XX.R01-02..HXZ    1.16E-02    1.71E-02    6.76E-01   -3.91E-01
1   XX.R01-02..BXY XX.R01-02..HXY    1.14E-02    1.59E-02    7.17E-01   -3.32E-01
4   XX.R01-02..BXX XX.R01-02..HXX    3.99E-02    5.51E-02    7.24E-01   -3.23E-01
6   XX.R01-01..BXZ XX.R01-01..HXZ    7.18E-04    8.43E-05    8.52E+00    2.14E+00
0   XX.R01-01..BXY XX.R01-01..HXY    9.60E-04    7.19E-05    1.34E+01    2.59E+00
8   XX.R01-01..BXX XX.R01-01..HXX    4.98E-02    7.03E-02    7.08E-01   -3.45E-01
```

Can you try again with the latest `devel` branch of the code and see if the issue persists?

One important note is that in #139 I changed a few things that will affect the way you call RecSec, namely that you can drop the `--overwrite` flag (this is now turned on by default), and you can drop `--preprocess both` (this is now True by default, so both streams are processed automatically). A new call would then look like:

```bash
recsec --pysep_path ./E_force_axi/ --syn_path ./E_force/ --source ./FORCESOLUTION --stations ./STATIONS --synsyn --sort_by azimuth --scale_by global_norm  --min_period_s 2 --components X,Y,Z
```

Let me know how that goes!

**Comment by ammcpherson** [comment]
Hi @bch0w,

I updated an instance of pysep and tried this out again - and I am not seeing the same issue! 

Thanks, and sorry for the false alarm.
