### ISSUE TITLE
Problem with subsetting stations for data/syn record sections, when using the --legacy_naming flag

### ISSUE THREAD

**Issue by ammcpherson** [adjtomo/pysep#141]
While attempting to make a record section comparing data and synthetics from SPECFEM3d_Globe, I encounter the following error:

```
[2024-03-14 13:51:53] - pysep - WARNING: stream lengths don't match 405 != 192 will subset to the shorter length
[2024-03-14 13:51:53] - pysep - DEBUG: stream subset removes 102 traces from 'st_a'
[2024-03-14 13:51:53] - pysep - DEBUG: stream subset removes 69 traces from 'st_b'

Traceback (most recent call last):
  File "/opt/miniconda3/envs/pysep_test/bin/recsec", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/amanda/REPOSITORIES/testing/pysep/pysep/recsec.py", line 2519, in main
    plotw_rs(**vars(parser.parse_args()))
  File "/Users/amanda/REPOSITORIES/testing/pysep/pysep/recsec.py", line 2480, in plotw_rs
    rs = RecordSection(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amanda/REPOSITORIES/testing/pysep/pysep/recsec.py", line 529, in __init__
    self.check_parameters()
  File "/Users/amanda/REPOSITORIES/testing/pysep/pysep/recsec.py", line 684, in check_parameters
    self.st, self.st_syn = subset_streams(self.st, self.st_syn)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amanda/REPOSITORIES/testing/pysep/pysep/utils/curtail.py", line 368, in subset_streams
    assert(len(st_a_out) == len(st_b_out)), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: station subsetting failed to return the same number of streams. check that your data does not contain multiple traces for a single component as this can lead to this error message
```

I dug into pysep/utils/curtail.py a little bit, and found that when I print out a subset of `st_a_out` and `st_b_out` from [this for loop](https://github.com/adjtomo/pysep/blob/devel/pysep/utils/curtail.py#L351-L356), I see that `st_a_out` is getting multiples for the same station and component:

```
AK.MCK..BHR  | 2024-01-19T21:33:15.088395Z - 2024-01-19T21:39:55.068395Z | 50.0 Hz, 20000 samples
AK.MCK..BHR  | 2024-01-19T21:33:15.088393Z - 2024-01-19T21:39:55.068393Z | 50.0 Hz, 20000 samples
AK.RIDG..BHR | 2024-01-19T21:33:15.088393Z - 2024-01-19T21:39:55.068393Z | 50.0 Hz, 20000 samples
AK.RIDG..BHR | 2024-01-19T21:33:15.088395Z - 2024-01-19T21:39:55.068395Z | 50.0 Hz, 20000 samples
AK.WAT7..BHR | 2024-01-19T21:33:15.088393Z - 2024-01-19T21:39:55.068393Z | 50.0 Hz, 20000 samples
AK.WAT7..BHR | 2024-01-19T21:33:15.088395Z - 2024-01-19T21:39:55.068395Z | 50.0 Hz, 20000 samples
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
6 Trace(s) in Stream:
AK.MCK..BXR  | 2024-01-19T21:34:54.966000Z - 2024-01-19T21:41:26.952000Z | 71.4 Hz, 28000 samples
AK.RIDG..BXR | 2024-01-19T21:34:54.966000Z - 2024-01-19T21:41:26.952000Z | 71.4 Hz, 28000 samples
AK.WAT7..BXR | 2024-01-19T21:34:54.966000Z - 2024-01-19T21:41:26.952000Z | 71.4 Hz, 28000 samples
AK.PAX..BXR  | 2024-01-19T21:34:54.966000Z - 2024-01-19T21:41:26.952000Z | 71.4 Hz, 28000 samples
AK.MLY..BXZ  | 2024-01-19T21:34:54.966000Z - 2024-01-19T21:41:26.952000Z | 71.4 Hz, 28000 samples
AK.I27K..BXT | 2024-01-19T21:34:54.966000Z - 2024-01-19T21:41:26.952000Z | 71.4 Hz, 28000 samples
```

What I also noticed is that each trace in `st_a_out` has slightly different start and end times. 

I am on the latest devel branch, and if I recall correctly, I have encountered this bug before, and it is solved by removing the stream.ms file that PySEP creates. I tried this, and it does indeed solve my issue. However, it would be nice to have this fixed in the code for the future. 

From personal communication:

> RecSec tries to blindly read everything in the directory you pass to `--pysep_path`, and since the legacy file saving puts all the SAC files and the `[stream.ms](http://stream.ms/)` in the same directory, it ends up reading the miniseed file too, which has no SAC headers. So RecSec is doubly reading the data, and then throwing the error you see when it tries to check the SAC headers on the miniseed data.

Thank you,
-Amanda

**Comment by bch0w** [comment]
Thanks for bringing this up @ammcpherson, I think I tried to address this in #127 with the `wildcard` parameter, which allows you to change how RecSec looks for data. Wondering if you try the following, does that fix things?

```bash
recsec --wildcard '*.?'  # plus all the other options you would normally use
```
That wildcard parameter should ignore the 'stream.ms' file and just look for formatting matching the SAC files.

Let me know how that goes!

**Comment by ammcpherson** [comment]
I just attempted this, and with the wildcard it can no longer read in the synthetics from SPECFEM, unfortunately.

**Comment by bch0w** [comment]
Oh! There is a separate `syn_wildcard` that defaults to `wildcard`'s value if not set. How about this?

```bash
recsec --wildcard '*.?'  --syn_wildcard '*' # plus all the other options you would normally use
```

**Comment by ammcpherson** [comment]
Hi @bch0w,

The two separate wildcard flags seems to have done the trick! Thank you

-Amanda

**Comment by bch0w** [comment]
No problem, closing as complete!
