### ISSUE TITLE
Data download for the moment tensor

### ISSUE THREAD

**Issue by iiiooooo** [adjtomo/pysep#142]

**Comment by bch0w** [comment]
Hi @iiiooooo, thanks for raising this. Your tests look fine so I I think we can assume the install is correct. 

I am not familiar with the required files for MTTime, can you please elaborate on what files you need in particular for your moment tensor inversion? 

Please note that PySEP is a standalone tool and while it has capability produce some files required by MTUQ (https://github.com/uafgeotools/mtuq), it will not be plug and play with all MT inversion codes.

**Comment by iiiooooo** [comment]
Sir i need

stations xml files
waveform mseed files (t,r,z)
Datetime csv
station csv

**Comment by bch0w** [comment]
Unfortunately PySEP will **not** natively create any of these files as it was not designed to interface with MTTime. However, you likely have enough data from the default PySEP outputs to create these files on your own, manually. 

If you would like to see these features implemented in future versions you are welcome to open a new issue requesting that, but I can't guarantee that will happen anytime soon as it is not a major priority.

**Comment by iiiooooo** [comment]
Sir can you sent me the basic code to download earthquake data (like stations, waveform)

**Comment by bch0w** [comment]
```bash
pysep -p mtuq_workshop_2022 -e 2017-09-03T033001_NORTH_KOREA.yaml
```

https://pysep.readthedocs.io/en/latest/pysep.html
