### ISSUE TITLE
Incorrect sorting of distances in CAP weight file with weights_dist option

### ISSUE THREAD

**Issue by thurinj** [adjtomo/pysep#144]
Hi @bch0w ,

Here's a quick unintended behavior I found using the weights_dist option to write the CAP file from pysep:
<img width="834" alt="image" src="https://github.com/adjtomo/pysep/assets/63735192/8476658b-e9ee-4aee-ac54-4679cf8e06c1">

It seems that it is using string-based sorting and it messes up with the ordering when moving from 10~ to 100~ and 100~ to 1000~ (distance is the second column, in km).

**Comment by bch0w** [comment]
Hopefully I didn't jump the gun by doing the full version release but I think I fixed this in #145, let me know if that looks good on your end!

**Comment by thurinj** [comment]
Looks all good to me, thanks for the lightning-fast fix ⚡!
