### ISSUE TITLE
geometrical spreading correction

### ISSUE THREAD

**Issue by carltape** [adjtomo/pysep#50]
In most cases, we should be plotting record sections that are corrected for geometric spreading. There were a few different options in the original code, such as controlling the exponent (surface waves or body waves). Another issue is that for some data sets, you want to exclude certain stations, such as basin stations (whose amplitudes are dominated by local structure, not the epicentral distance). Here is an example figure from Smith and Tape (2019), showing Cook Inlet basins in red that were excluded from the calculation of the geometric spreading factor.

![image (7)](https://user-images.githubusercontent.com/4455456/199577789-138001c9-afa8-431d-adcd-f9d5e2ef3af8.png)

Probably the simplest way would be to pass a set of station names to be excluded from the calculation of geometrical spreading. Or: subset the stations first, get the correction factor, then pass the correction factor as an input argument into pysep. Thank you!

**Comment by bch0w** [comment]
Summarizing tasks
- [ ] Option to correct for geometric spreading
- [ ] Allow User to exclude station by choice

**Comment by bch0w** [comment]
This is now roughly implemented in feature branch 'feature_geometric_spreading'. Still some weird behavior when waveforms are not properly scaled (e.g., AVO stations in 2009 anchorage event) but putting a progress report comment here

Checklist
----------
- [x]  Allow User to set geometric spreading factor (optional k-val)
- [x]  On the fly calculate geometric spreading reduction and generate figure as show in figure shown by @carltape
- [x]  Allow User to exclude stations by name (parameter geo_fac_exclude?), which would ignore these stations when calculating k-val

Scaling by global norm (no geometric spreading) for a well-behaved subset of stations for the 2009 Anchorange example
![scale_by_global_norm](https://user-images.githubusercontent.com/23055374/200429160-430a4b2b-bd07-4701-b085-63a74200184b.png)

Scaling by geometric spreading for the same subset:
![scale_by_geo_spread](https://user-images.githubusercontent.com/23055374/200429357-6b1fb301-cb4b-4a69-b4cb-f582292b761e.png)

Geometric spreading plot:
![geometric_spreading](https://user-images.githubusercontent.com/23055374/200429526-ba66fb5a-72be-4607-9b17-6e126b1b95c2.png)

**Comment by bch0w** [comment]
This is implemented in the devel branch in #52
