### ISSUE TITLE
feature request: ObsPy mass downloader

### ISSUE THREAD

**Issue by vsilwal** [adjtomo/pysep#62]
Just wanted to check whether the mass_downloader option has been removed from pysep. If so, is pysep able to handle requests when user wants data from multiple data centres?

**Comment by bch0w** [comment]
Hi Vipul, the mass_downloader option did not make it through the PySEP refactor although I'm not sure why I didn't address it. 

Is this a feature you would find useful? If so we could change this issue to a feature request to reinstate the mass download option, it should be a quick addition. For the moment a workaround would be to run PySEP multiple times with wildcards on the network and station, manually changing the client each time.

**Comment by vsilwal** [comment]
Yes, mass_downloader option is useful for us.

Thanks,

**Comment by bch0w** [comment]
Task: bring back the mass downloader option that was present previously in PySEP

https://github.com/adjtomo/pysep/blob/d5f594b603c265f9186725263fe2b3ac5fb5c7f4/getwaveform.py#L584-L636

which takes advantage of ObsPy's mass downloader:

https://docs.obspy.org/packages/autogen/obspy.clients.fdsn.mass_downloader.html

**Comment by bch0w** [comment]
Hi @vsilwal, I've just PR'ed the ``devel`` branch with the mass downloader function from old PySEP 

https://github.com/adjtomo/pysep/blob/952c7d7c54072e26bddafb31a4968fde671c2c26/pysep/pysep.py#L736-L829

See the new docs page for how to use: https://github.com/adjtomo/pysep/wiki/3.-PySEP-via-the-Command-Line#obspy-mass-downloader
 
I tested it out with a test Config file (https://github.com/adjtomo/pysep/blob/devel/pysep/configs/test/test_mass_download.yaml) and things worked fine. Could you test it out and let me know if it works as expected? If so then I'll close out this issue.

**Comment by vsilwal** [comment]
Yes this seems to be working. I am closing the issue.
