### ISSUE TITLE
station selection option

### ISSUE THREAD

**Issue by carltape** [adjtomo/pysep#79]
There is an unusual case for station selection whereby one might want to have a set of stations defined by 6 numbers: a central longitude and latitude point (not necessarily the epicenter), a min and max epicentral distance, and a min and max azimuth. This was implemented in the original matlab code [here](https://github.com/uafgeotools/GEOTOOLS/blob/master/matlab_util/util_data_syn/getwaveform.m#L655) (private repo). We used it for one example in GEOS 626, where we want a set of stations in Alaska related to triggering from the 2012 Indian Ocean earthquake.

**Comment by bch0w** [comment]
This should be possible with ObsPy's `get_stations` function, which takes a bounding box region and wildcard network and station (https://docs.obspy.org/packages/autogen/obspy.clients.fdsn.client.Client.get_stations.html)

**Comment by bch0w** [comment]
Ah, I missed the part about azimuth. Understood, then how I understand it, this shouldn't be directly part of the data gathering routines, but rather exist as some utility function that takes bounding box and/or azimuth and cuts an Inventory with matching stations. 

I wrote some similar things for catalogs in the Decluster class, can probably repurpose or separate these capabilities into standalone functions that can be imported and used by a User:

Cutting by min/max azimuth
https://github.com/adjtomo/pysep/blob/3f5d7ab12aee663abe907036ca6eb757879d3722/pysep/declust.py#L752-L771

**Comment by carltape** [comment]
After further thought, I think that adding these new variables (reference lon/lat) would not be worth having, given the limited use it would see.
