### ISSUE TITLE
improve source receiver map plotting

### ISSUE THREAD

**Issue by carltape** [adjtomo/pysep#82]
Currently the nice station map in pysep is associated with the data request. However, a user who plots a subset of stations in a record section will want to see a station map containing the subset of stations (only). Is there a way to call the map-plotting from inside plotw_rs, for example? Or how can this be achieved? It's okay if the extra map is cruder than the fancier version.

This map would be very helpful for the GEOS 626 course at UAF. Thanks.

**Comment by bch0w** [comment]
@aakash10gupta @carltape 

Since record section doesn't use the event and station metadata (Catalog and Inventory), we do not have access to the nice ObsPy maps from PySEP which require these information. 

I could make a very crude map using the information in the SAC headers, but it feels redundant to do this since we already have the mapping capability.

Can I suggest an alternative, add the following code block in your GEOS626 notebooks that uses the metadata written out by PySEP to create a subset map. 

```python
from obspy import read_events, read_inventory, Inventory
from pysep.utils.plot import plot_source_receiver_map

station_list = ["ASCN", "PFO", "KDAK"]

# these should be located in the PySEP output directory
event = read_events("event.xml")[0]
inv_original = read_inventory("inv.xml")

# subset stations from inventory
inv_plot = Inventory()
for station in station_list:
    inv_plot += inv.select(station=station)

plot_source_receiver_map(inv, event)
```
Let me know if that works for your purposes

**Comment by aakash10gupta** [comment]
> I could make a very crude map using the information in the SAC headers, but it feels redundant to do this since we already have the mapping capability.

I think the idea here is that when a user has selected their streams for plotting a record section, the user would want to see the locations of the selected stations on a map simultaneously, for better interpretation. This might be redundant code but I also see how the station distribution map showing up naturally with record section plotting calls would help. Probably something to discuss more?

**Comment by aakash10gupta** [comment]
I see that https://github.com/adjtomo/pysep/issues/82 suggests that there is an even quicker option available for the users now with the subset option in the function `plot_source_receiver_map`. If providing the record section plotting tool with access to this function is infeasible, then maybe the users can be pointed to this function in the record section plotting documentation. But in case it's feasible, the preferred option for the user will be to have it within the record section plotter.

**Comment by bch0w** [comment]
Thanks @aakash10gupta, I understand the use case, but I still think this will require unnecessary overhead in the record section tool for something that can be accomplished in a few lines outside of it. I am happy to place this in the documentation connected with the record section tool as an alternative.

That being said, if you would really like to see this feature implemented, you're welcome to submit a pull request with proposed changes. If you need, I can help come up with a general guideline for implementation.

**Comment by aakash10gupta** [comment]
@bch0w I think a note in the documentation would be fine given the unnecessary overhead that you mention will be needed for implementing this feature. This request can be closed otherwise.

**Comment by aakash10gupta** [comment]
Now that we have this alternative documented, I think we can close this issue.
