### ISSUE TITLE
location code overridden during data selection  and download

### ISSUE THREAD

**Issue by aakash10gupta** [adjtomo/pysep#86]
When a data download request is made with the location code specified, pysep seems to ignore the provided location code and uses the wildcard instead to search for and download data.

**Comment by bch0w** [comment]
Thanks for catching this @aakash10gupta, bugfix has been pushed in https://github.com/adjtomo/pysep/commit/1f3f125e51e8a49d7b061338f43e822b6760eba5 

Please have a look and see if that fixed the issue

**Comment by aakash10gupta** [comment]
Looks like this is working fine now with the update.
