### ISSUE TITLE
display pysep version in DEBUG output

### ISSUE THREAD

**Issue by carltape** [adjtomo/pysep#95]
At the start of the debug output lines, could something be printed regarding the version of pysep (or the version of the github code)? This is a typical sequence of lines:
<img width="865" alt="Screen Shot 2023-03-03 at 6 17 07 AM" src="https://user-images.githubusercontent.com/4455456/222757532-27ec5a25-0b32-4979-8e15-db06e2addca6.png">

**Comment by bch0w** [comment]
Hi @carltape, this is addressed by #97
