### ISSUE TITLE
Data download for a 'list' of station IDs

### ISSUE THREAD

**Issue by aakash10gupta** [adjtomo/pysep#98]
In some analyses it is useful to have the option to download data for a specific station ID given by network.station.location.channel. While this can be done with the present package the ID needs to be split into 4 components before being provided as an input to PySEP. The user has to create a loop when there is a 'list' of station IDs for which the data needs to be download. Separate associated files - event.xml, inv.xml, etc are generated for each Pysep call. It will be very helpful if PySEP can accept a list or comma separated strings of station IDs as inputs for one download call.

**Comment by bch0w** [comment]
This was implemented in #105, see accompanying docs for how to use:
https://pysep.readthedocs.io/en/devel/pysep.html#select-trace-id-input

**Comment by aakash10gupta** [comment]
This is a great feature! I tested the update and it is working fine.
